on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions/attest@v4
        with:
          subject-path: README.md
