on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: scop/common/force-color@main
      - run: |
          echo "GIT_CONFIG_PARAMETERS='color.ui=always'${GIT_CONFIG_PARAMETERS:+ $GIT_CONFIG_PARAMETERS}" >>"$GITHUB_ENV"
      - run: env
      - uses: actions/checkout@v6
      - run: git status
      - uses: jdx/mise-action@v3
      - run: "dprint check || :"
      - run: "mise exec -- prek run --all-files || :"
      - run: "mise exec -- pre-commit run --all-files || :"
      - run: "mise exec -- rg test README.md || :"
      - run: "mise exec -- rumdl check README.md || :"
      - run: "mise exec -- shellcheck test.sh || :"
      - run: "mise exec -- uv foo 2>&1 || :"
      - run: "mise exec -- aqua i || :"

  windows-test:
    runs-on: windows-latest
    steps:
      - run: |
          echo hello > world
          sha256sum world
          sha256sum --help
          shasum -a 256 world
          shasum --help
