on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #- uses: scop/common/force-color@main
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: "dprint check || :"
      - run: "mise exec -- prek run --all-files || :"
      - run: "mise exec -- pre-commit run --all-files || :"
      - run: "mise exec -- rg test README.md || :"
      - run: "mise exec -- rumdl check README.md || :"
      - run: "mise exec -- shellcheck test.sh || :"
      - run: "mise exec -- env CLICOLOR_FORCE=1 uv foo 2>&1 || :"
