on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: scop/common/force-color@main
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: "dprint check || :"
      - run: "mise exec -- prek run --all-files || :"
      - run: "mise exec -- pre-commit run --all-files || :"
